apiVersion: v1
kind: Pod
metadata:
  name: ms-token-exchange-env
  labels:
    name: ms-token-exchange-env
spec:
  containers:
  - name: ms-token-exchange-env
    image: forgerock-docker-public.bintray.io/microservice/token-exchange:ENVCONSUL
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ms-token-exchange-env
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30107
  selector:
    name: ms-token-exchange-env
